name: Dart CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.KEY_JKS }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
        #     - name: analyse build
        #       run: flutter analyze .

      - name: Generate build
        run: flutter build appbundle
        env:
          KEY_JKS: key.jks
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
        #        run: echo $KEY_JKS > key.jks

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: final_aab
          path: build/app/outputs/bundle/release/app.aab
